language: ruby

sudo: false

rvm: 2.5.1

before_script:
  - 'RAILS_ENV=test bundle exec rake db:create --trace'
  - 'RAILS_ENV=test bundle exec rake db:test:prepare_sequential'

script: "bundle exec parallel-rspec spec"

cache: bundler

addons:
  postgresql: 9.6

services:
  - redis-server
