# This is only used for standalone_migrations. In other contexts
# Travis.config.database will be used.

defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning
  username: <%= ENV['USER'] %>
  host: localhost

production:
  <<: *defaults
  database: travis_development
  logs_database: travis_logs_development

development:
  <<: *defaults
  database: travis_development
  logs_database: travis_logs_development

test:
  <<: *defaults
  database: travis_test
  logs_database: travis_logs_test
